export enum OtpTypes {
  FORGET_PASSWORD = "FORGET_PASSWORD",
  LOGIN_WITH_MOBILE = "LOGIN_WITH_MOBILE",
  LOGIN_WITH_EMAIL = "LOGIN_WITH_EMAIL",
  VERIFY_COMPANY = "VERIFY_COMPANY",
  VERIFY = "VERIFY",
  INTRODUCE_SELF = "INTRODUCE_SELF",
}
